shared:
    image: node:12
    steps:
      - job: echo "hello $SD_JOB_NAME"
jobs:
    main:
        requires: [~pr, ~commit]
    hr-1:
        annotations:
            screwdriver.cd/buildPeriodically: "H(20-20) * * * *"
    hr-2:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-3:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(30-45) * * * *"
    hr-4:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-5:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-6:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-7:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-8:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-9:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-10:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-11:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-12:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-13:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-14:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-15:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-16:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-17:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-18:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-19:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-20:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-21:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-22:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-23:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-24:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-25:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-26:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-27:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-28:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-29:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-30:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-31:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-32:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-33:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-34:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-35:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-36:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-37:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-38:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-39:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-40:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-51:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-52:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-53:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-54:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-55:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-56:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-57:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-58:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-59:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-60:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-71:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-72:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-73:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-74:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-75:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-76:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-77:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-78:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-79:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-80:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-81:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-82:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-83:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-84:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-85:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-86:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-87:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-88:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-89:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-90:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-91:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-92:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-93:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-94:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-95:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-96:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-97:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-98:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-99:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    hr-100:
        annotations:         
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
